apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nkdagalcw-go 
  janus-idp.io/tekton: nkdagalcw-go
  backstage.io/kubernetes-id: nkdagalcw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkdagalcw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  